import DBHandler as db

db.create_db()
db.insert_user("Chat","Miaou")
db.insert_user("Chien","Wouf")
db.insert_user("Loup", "Aouh")
db.insert_user("Chat","Miaou")
db.is_user_on_db("Chat", "Miaou")
db.is_user_on_db("Chien", "Wouaf")
db.is_user_on_db("Loup", "Aouu")
db.insert_decoupe("Bonjour", "Chat", "192.168.0.0", None)
db.insert_decoupe("Bonjour", "Chat", "192.168.0.0", "255.255.0.0")
db.insert_sous_reseau(0, 5, "Bonjour", "Chat")
db.insert_sous_reseau(1, 5, "Bonjour", "Chat")
db.insert_sous_reseau(2, 5, "Bonjour", None)
db.insert_sous_reseau(3, 7, "Bonjour", "Chat")
print(db.get_user_subnetting("Chat", "Bonjour"))
print(db.get_user_specified_subnet("Chat", "Bonjour", 0))